export const MODULE_LIST_REQUEST = "MODULE_LIST_REQUEST";
export const MODULE_LIST_SUCCESS = "MODULE_LIST_SUCCESS";
export const MODULE_LIST_FAIL = "MODULE_LIST_FAIL";

export const MODULE_CREATE_REQUEST = "MODULE_CREATE_REQUEST";
export const MODULE_CREATE_SUCCESS = "MODULE_CREATE_SUCCESS";
export const MODULE_CREATE_FAIL = "MODULE_CREATE_FAIL";

